sign-commit = true

pre-release-commit-message = "Version {{version}}"
tag-message = "{{crate_name}} version {{version}}"

pre-release-replacements = [
  {file="README.md", search="firefly-iii = .*", replace="firefly-iii = \"{{version}}\""},
]
